[ClickHouse]
Addr = "localhost:9000"         # 服务地址
Database = "hera"               # 数据库
Username = ""                   # 用户名
Password = ""                   # 密码
DialTimeout = 10                # 链接超时时间，单位 s
MaxOpenConns = 32               # 最大打开链接输
MaxIdleConns = 16               # 最大空闲连接数
ConnMaxLifeTime = 3600          # 最大连接存活时长 单位 s
BatchInterval = 10              # 批量入库间隔 单位 s
BatchSize = 10                  # 批量入库数量
