version: "2.4"
services:
    db:
        image: postgres:12
        container_name: db
        cpuset: 1-2
        logging:
            options:
                max-size: 10m
                max-file: "10"
        environment:
            POSTGRES_USER: hera
            POSTGRES_PASSWORD: hera
            POSTGRES_DB: hera
        command:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
        volumes:
            - ./workdir/pg_data:/var/lib/postgresql/data
            - ./workdir/pg_host:/host
            - ./config/hera/prod_init.sql:/host_init/prod_init.sql
            - /etc/localtime:/etc/localtime:ro
            - ./config/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
        mem_limit: "0"
        restart: always
        networks:
            app_net:
                ipv4_address: 172.15.1.10
        ports:
            - 127.0.0.1:5432:5432
    redis:
        image: redis:7.0
        container_name: redis
        restart: always
        ulimits:
            nproc: 1048576
            nofile: 1048576
        logging:
            options:
                max-size: 10M
                max-file: "10"
        command:
            - redis-server
            - --requirepass
            - e585a8e68289e7899b624032303231
        volumes:
            - ./workdir/redis_data:/data
            - /etc/localtime:/etc/localtime:ro
        mem_limit: "0"
        networks:
            app_net:
                ipv4_address: 172.15.0.61
networks:
    app_net:
        name: app_net
        ipam:
            config:
                - subnet: 172.15.0.0/16
